import { type Locator, type Page } from "@playwright/test";
import * as fs from "fs";
import * as path from "path";

interface StepRecord {
  number: number;
  title: string;
  description: string;
  screenshotPath: string;
}

export interface StepOptions {
  waitAfter?: number;
  highlightTarget?: Locator;
}

interface LocaleStrings {
  autoGenerated: (date: string) => string;
  stepPrefix: (num: string) => string;
}

const locales: Record<string, LocaleStrings> = {
  ja: {
    autoGenerated: (date) => `自動生成日: ${date}`,
    stepPrefix: (num) => `手順 ${num}`,
  },
  en: {
    autoGenerated: (date) => `Auto-generated on ${date}`,
    stepPrefix: (num) => `Step ${num}`,
  },
};

const DEFAULT_HIDE_OVERLAY_SELECTORS = [
  "nextjs-portal { display: none !important; }",
  "[data-nextjs-dialog-overlay] { display: none !important; }",
  "[data-nextjs-toast] { display: none !important; }",
];

export type OutputFormat = "md" | "pdf" | "both";

export interface PdfOptions {
  format?: "A4" | "Letter" | "Legal";
  printBackground?: boolean;
  margin?: { top?: string; right?: string; bottom?: string; left?: string };
}

export interface ScenarioRecorderOptions {
  /** Output locale (default: "ja") */
  locale?: "ja" | "en";
  /**
   * CSS rules to hide framework dev overlays during screenshots.
   * Defaults to Next.js overlay selectors (nextjs-portal, etc.).
   * Pass custom selectors for other frameworks (Nuxt, Vite, etc.).
   */
  hideOverlaySelectors?: string[];
  /** Output format (default: "md") */
  outputFormat?: OutputFormat;
  /** PDF generation options (Chromium only) */
  pdfOptions?: PdfOptions;
}

export class ScenarioRecorder {
  private page: Page;
  private scenarioName: string;
  private title: string;
  private outputDir: string;
  private steps: StepRecord[] = [];
  private screenshotDir: string;
  private locale: LocaleStrings;
  private hideOverlaySelectors: string[];
  private outputFormat: OutputFormat;
  private pdfOptions: PdfOptions;

  constructor(
    page: Page,
    scenarioName: string,
    title: string,
    outputDir: string,
    options?: ScenarioRecorderOptions
  ) {
    this.page = page;
    this.scenarioName = scenarioName;
    this.title = title;
    this.outputDir = outputDir;
    this.screenshotDir = path.join(outputDir, "screenshots", scenarioName);
    this.locale = locales[options?.locale ?? "ja"];
    this.hideOverlaySelectors =
      options?.hideOverlaySelectors ?? DEFAULT_HIDE_OVERLAY_SELECTORS;
    this.outputFormat = options?.outputFormat ?? "md";
    this.pdfOptions = options?.pdfOptions ?? {};
    fs.mkdirSync(this.screenshotDir, { recursive: true });
  }

  configure(overrides: { scenarioName?: string; title?: string; outputDir?: string }): void {
    if (this.steps.length > 0) {
      throw new Error("configure() must be called before any step() calls");
    }
    if (overrides.scenarioName !== undefined) {
      this.scenarioName = overrides.scenarioName;
    }
    if (overrides.title !== undefined) {
      this.title = overrides.title;
    }
    if (overrides.outputDir !== undefined) {
      this.outputDir = overrides.outputDir;
    }
    this.screenshotDir = path.join(this.outputDir, "screenshots", this.scenarioName);
    fs.mkdirSync(this.screenshotDir, { recursive: true });
  }

  async step(
    title: string,
    description: string,
    action: (page: Page) => Promise<void>,
    options?: StepOptions
  ) {
    await action(this.page);

    if (options?.waitAfter) {
      await this.page.waitForTimeout(options.waitAfter);
    }

    await this.page.waitForLoadState("domcontentloaded");

    if (options?.highlightTarget) {
      await this.addHighlight(options.highlightTarget);
    }

    await this.hideDevOverlay();

    const stepNum = this.steps.length + 1;
    const padded = String(stepNum).padStart(2, "0");
    const filename = `step-${padded}.png`;
    const screenshotPath = path.join(this.screenshotDir, filename);

    await this.page.screenshot({ path: screenshotPath, fullPage: false });

    await this.restoreDevOverlay();

    if (options?.highlightTarget) {
      await this.removeHighlight(options.highlightTarget);
    }

    this.steps.push({
      number: stepNum,
      title,
      description,
      screenshotPath: `./screenshots/${this.scenarioName}/${filename}`,
    });
  }

  generateMarkdown() {
    const date = new Date().toISOString().slice(0, 10);
    const l = this.locale;
    const lines: string[] = [
      `# ${this.title}`,
      "",
      `> ${l.autoGenerated(date)}`,
      "",
    ];

    for (const s of this.steps) {
      const padded = String(s.number).padStart(2, "0");
      lines.push(`## ${l.stepPrefix(padded)}: ${s.title}`);
      lines.push("");
      lines.push(s.description);
      lines.push("");
      lines.push(`![${l.stepPrefix(padded)}](${s.screenshotPath})`);
      lines.push("");
    }

    const mdPath = path.join(this.outputDir, `${this.scenarioName}.md`);
    fs.writeFileSync(mdPath, lines.join("\n"), "utf-8");
  }

  private buildHtml(): string {
    const date = new Date().toISOString().slice(0, 10);
    const l = this.locale;
    const stepsHtml = this.steps
      .map((s) => {
        const padded = String(s.number).padStart(2, "0");
        const absPath = path.resolve(this.outputDir, s.screenshotPath);
        const imgData = fs.readFileSync(absPath);
        const base64 = imgData.toString("base64");
        const dataUri = `data:image/png;base64,${base64}`;
        return `
      <div style="page-break-inside: avoid; margin-bottom: 24px;">
        <h2>${l.stepPrefix(padded)}: ${s.title}</h2>
        <p>${s.description}</p>
        <img src="${dataUri}" alt="${l.stepPrefix(padded)}" style="max-width: 100%;" />
      </div>`;
      })
      .join("\n");

    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: sans-serif; margin: 40px; }
    h1 { margin-bottom: 4px; }
    .meta { color: #666; margin-bottom: 24px; }
    img { max-width: 100%; }
  </style>
</head>
<body>
  <h1>${this.title}</h1>
  <p class="meta">${l.autoGenerated(date)}</p>
  ${stepsHtml}
</body>
</html>`;
  }

  async generatePdf(options?: PdfOptions): Promise<void> {
    const browserName = this.page.context().browser()?.browserType().name();
    if (browserName && browserName !== "chromium") {
      throw new Error(
        `generatePdf() is only supported on Chromium. Current browser: ${browserName}`
      );
    }

    const html = this.buildHtml();
    await this.page.setContent(html, { waitUntil: "load" });

    const merged: PdfOptions = { ...this.pdfOptions, ...options };
    await this.page.pdf({
      path: path.join(this.outputDir, `${this.scenarioName}.pdf`),
      format: merged.format ?? "A4",
      printBackground: merged.printBackground ?? true,
      margin: merged.margin ?? {
        top: "20mm",
        right: "20mm",
        bottom: "20mm",
        left: "20mm",
      },
    });
  }

  async generate(): Promise<void> {
    if (this.outputFormat === "md" || this.outputFormat === "both") {
      this.generateMarkdown();
    }
    if (this.outputFormat === "pdf" || this.outputFormat === "both") {
      await this.generatePdf();
    }
  }

  private async hideDevOverlay() {
    try {
      const selectors = this.hideOverlaySelectors;
      await this.page.evaluate((css: string[]) => {
        const style = document.createElement("style");
        style.id = "__scenario-hide-dev-overlay";
        style.textContent = css.join("\n");
        document.head.appendChild(style);
      }, selectors);
    } catch {
      // page may not be ready — skip
    }
  }

  private async restoreDevOverlay() {
    try {
      await this.page.evaluate(() => {
        document.getElementById("__scenario-hide-dev-overlay")?.remove();
      });
    } catch {
      // skip
    }
  }

  private async addHighlight(locator: Locator) {
    try {
      const el = await locator.elementHandle({ timeout: 5000 });
      if (el) {
        await el.evaluate((node: HTMLElement) => {
          node.dataset.origOutline = node.style.outline;
          node.style.outline = "3px solid red";
        });
        await el.dispose();
      }
    } catch {
      // element may be hidden or detached — skip
    }
  }

  private async removeHighlight(locator: Locator) {
    try {
      const el = await locator.elementHandle({ timeout: 5000 });
      if (el) {
        await el.evaluate((node: HTMLElement) => {
          node.style.outline = node.dataset.origOutline ?? "";
          delete node.dataset.origOutline;
        });
        await el.dispose();
      }
    } catch {
      // element may be hidden or detached — skip
    }
  }
}

export interface GenerateIndexOptions {
  dir: string;
  output?: string;
  locale?: "ja" | "en";
  title?: string;
}

const indexLocales: Record<string, string> = {
  ja: "操作手順書 一覧",
  en: "Scenario Manual Index",
};

export function generateIndex(options: GenerateIndexOptions): void {
  const { dir, locale = "ja" } = options;
  const outputPath = options.output ?? path.join(dir, "index.md");
  const heading = options.title ?? indexLocales[locale] ?? indexLocales.ja;

  const files = fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".md") && f !== path.basename(outputPath))
    .sort();

  const entries: { file: string; title: string }[] = [];
  for (const file of files) {
    const content = fs.readFileSync(path.join(dir, file), "utf-8");
    const match = content.match(/^#\s+(.+)$/m);
    const title = match ? match[1] : file.replace(/\.md$/, "");
    entries.push({ file, title });
  }

  entries.sort((a, b) => a.title.localeCompare(b.title));

  const lines: string[] = [`# ${heading}`, ""];
  for (const entry of entries) {
    lines.push(`- [${entry.title}](./${entry.file})`);
  }
  lines.push("");

  fs.writeFileSync(outputPath, lines.join("\n"), "utf-8");
}
